FROM tomcat:7.0
# allow bamboo to interact with tomcat
# ref: https://confluence.atlassian.com/bamboo/using-tomcat-with-bamboo-for-continuous-deployment-305759758.html
ADD tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
